# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
gems:
  - octopress-codeblock # {% codeblock lang:ruby title:"Check if a number is prime" mark:3 %} \n {% endcodeblock %}
  - octopress-codefence # ```ruby mark:2-4 title:"Testing codefence" url:"https://github.com/octopress/codefence" link_text:"plugin link" -------- ```
  - octopress-image-tag # {% img left half http://site.com/images/ninja.png title:"Hidden Ninja" %}
  - octopress-quote-tag # {% quote author:"Bob McAwesome" url:http://example.com title:"Great Wisdom" %} --------- {% endquote %}
  - octopress-solarized
  - octopress-social # https://github.com/octopress/social
#  - octopress-linkblog # https://github.com/octopress/linkblog
  - octopress-filter-tag # https://github.com/octopress/filter-tag
  - octopress-filters # https://github.com/octopress/filters
  - octopress-comment-tag # {% _ This is a comment! %}
  - jekyll-sitemap

linkblog:
  linkpost:
    marker: →
    marker_position: after
  posts:
    marker: false
    marker_position: before

  titlecase: true
  unorphan: true
  permalink_label: Permalink
