# Site settings
title: prashanthr.net
description: >
  Random things I work upon
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://prashanthr.net" # the base hostname & protocol for your site
twitter_username: prash_raj
github_username:  prashanthrajagopal

# Build settings
markdown: kramdown
gems:
  - octopress-codeblock # {% codeblock lang:ruby title:"Check if a number is prime" mark:3 %} \n {% endcodeblock %}
  - octopress-codefence # ```ruby mark:2-4 title:"Testing codefence" url:"https://github.com/octopress/codefence" link_text:"plugin link" -------- ```
  - octopress-image-tag # {% img left half http://site.com/images/ninja.png title:"Hidden Ninja" %}
  - octopress-quote-tag # {% quote author:"Bob McAwesome" url:http://example.com title:"Great Wisdom" %} --------- {% endquote %}
  - octopress-solarized
  - octopress-social # https://github.com/octopress/social
  - octopress-gist
  - octopress-filter-tag # https://github.com/octopress/filter-tag
  - octopress-filters # https://github.com/octopress/filters
  - octopress-comment-tag # {% _ This is a comment! %}
  - jekyll-sitemap
